"""
Django settings for iwinghire project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import datetime
from pathlib import Path

from .local import DATABASES
from .consts.apps import INSTALLED_APPS, MIDDLEWARE
from .consts.consts import (AUTH_PASSWORD_VALIDATORS, TEMPLATES, LANGUAGE_CODE)
from .consts.rest_framework import REST_FRAMEWORK

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r^4q1f%1_lx=z#srp5x-+yy7nf-rl09mg7de^-1eor(op1oj4^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# }
#
# SPECTACULAR_SETTINGS = {
#     'TITLE': 'IwingHire APIS',
#     'DESCRIPTION': 'IwingHire project description',
#     'VERSION': '1.0.0',
#     'SERVE_INCLUDE_SCHEMA': False
# }

ROOT_URLCONF = 'iwinghire.urls'

WSGI_APPLICATION = 'iwinghire.wsgi.application'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/home/ubuntu/iwinghire/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
